### Performance on Bauch test set

In [1]:
import pickle
import numpy as np
# load the data
with open("preproccessed_data_uncensored.pickle", "rb") as f:
    data_dic = pickle.load(f)

test = data_dic['test']
test_target = data_dic['test_target']

In [2]:
test = np.array(test)
test_target = np.array(test_target)

In [3]:
filter_list = [t>1 for t in test_target]
test = test[filter_list]
test_target = test_target[filter_list]

test_target[test_target == 3] = 0
test_target[test_target == 2] = 1

In [6]:
with open("amit_apply_bauch_test_uncencored.pickle", "rb") as f:
    amit_pred = pickle.load(f)

In [7]:
amit_pred = np.array(amit_pred)
amit_pred = amit_pred[filter_list]

In [8]:
test_preds = amit_pred

In [9]:
#performance on bauch uncensored
from sklearn.metrics import accuracy_score
test_preds = np.argmax(test_preds, axis=2)
print("accuracy: ", accuracy_score(test_target, test_preds))

from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print(classification_report(test_target, test_preds, digits=3))
print("F1 score:",f1_score(test_target, test_preds, average='macro'))
print("Precision: ",precision_score(test_target, test_preds, average="macro"))
print("Recall: ",recall_score(test_target, test_preds, average="macro"))    
print("Confusion matrix: \n",confusion_matrix(test_target, test_preds))

accuracy:  0.499
              precision    recall  f1-score   support

           0      0.444     0.008     0.016       500
           1      0.499     0.990     0.664       500

    accuracy                          0.499      1000
   macro avg      0.472     0.499     0.340      1000
weighted avg      0.472     0.499     0.340      1000

F1 score: 0.33985049787922034
Precision:  0.4719699517883171
Recall:  0.499
Confusion matrix: 
 [[  4 496]
 [  5 495]]


In [17]:
import pickle
import numpy as np
# load the data
with open("preproccessed_data.pickle", "rb") as f:
    data_dic = pickle.load(f)

test = data_dic['test']
test_target = data_dic['test_target']

In [18]:
test = np.array(test)
test_target = np.array(test_target)

filter_list = [t>1 for t in test_target]
test = test[filter_list]
test_target = test_target[filter_list]

test_target[test_target == 3] = 0
test_target[test_target == 2] = 1

In [19]:
with open("amit_apply_bauch_test_cencored.pickle", "rb") as f:
    amit_pred = pickle.load(f)

amit_pred = np.array(amit_pred)
amit_pred = amit_pred[filter_list]
test_preds = amit_pred    

In [20]:
#performance on bauch uncensored
from sklearn.metrics import accuracy_score
test_preds = np.argmax(test_preds, axis=2)
print("accuracy: ", accuracy_score(test_target, test_preds))

from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print(classification_report(test_target, test_preds, digits=3))
print("F1 score:",f1_score(test_target, test_preds, average='macro'))
print("Precision: ",precision_score(test_target, test_preds, average="macro"))
print("Recall: ",recall_score(test_target, test_preds, average="macro"))    
print("Confusion matrix: \n",confusion_matrix(test_target, test_preds))

accuracy:  0.511
              precision    recall  f1-score   support

           0      0.824     0.028     0.054       500
           1      0.506     0.994     0.670       500

    accuracy                          0.511      1000
   macro avg      0.665     0.511     0.362      1000
weighted avg      0.665     0.511     0.362      1000

F1 score: 0.36221079389757027
Precision:  0.6645622643767578
Recall:  0.511
Confusion matrix: 
 [[ 14 486]
 [  3 497]]


### Performance on noise induced test sets

In [2]:
import pickle
with open("train_amit/envn_uncen_resids_dic.pickle", "rb") as f:
    data_dic_t1 = pickle.load(f)

with open("train_amit/whiten_uncen_resids_dic.pickle", "rb") as f:
    data_dic_t2 = pickle.load(f)

with open("train_amit/demn_uncen_resids_dic.pickle", "rb") as f:
    data_dic_t3 = pickle.load(f)

In [3]:
test_envn = data_dic_t1['test']
test_envn_target = data_dic_t1['test_target']
test_whiten = data_dic_t2['test']
test_whiten_target = data_dic_t2['test_target']
test_demn = data_dic_t3['test']
test_demn_target = data_dic_t3['test_target']

In [4]:
import pickle
with open("amit_apply_test_demn.pickle", "rb") as f:
    preds_demn = pickle.load(f)

with open("amit_apply_test_whiten.pickle", "rb") as f:
    preds_whiten = pickle.load(f)

with open("amit_apply_test_envn.pickle", "rb") as f:
    preds_envn = pickle.load(f)


In [7]:
# uncensored prerofmance
from sklearn.metrics import accuracy_score
import numpy as np

test_demn_preds = np.argmax(preds_demn, axis=2)
test_whiten_preds = np.argmax(preds_whiten, axis=2)
test_envn_preds = np.argmax(preds_envn, axis=2)


from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print("############### Env noise")
print("envn test accuracy: ", accuracy_score(test_envn_target, test_envn_preds))
print(classification_report(test_envn_target, test_envn_preds, digits=3))
print("envn F1 score:",f1_score(test_envn_target, test_envn_preds, average='macro'))
print("envn Precision: ",precision_score(test_envn_target, test_envn_preds, average="macro"))
print("envn Recall: ",recall_score(test_envn_target, test_envn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_envn_target, test_envn_preds))

print("############### Dem noise")
print("demn test accuracy: ", accuracy_score(test_demn_target, test_demn_preds))
print(classification_report(test_demn_target, test_demn_preds, digits=3))
print("envn F1 score:",f1_score(test_demn_target, test_demn_preds, average='macro'))
print("envn Precision: ",precision_score(test_demn_target, test_demn_preds, average="macro"))
print("envn Recall: ",recall_score(test_demn_target, test_demn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_demn_target, test_demn_preds))

print("############### White noise")
print("whiten test accuracy: ", accuracy_score(test_whiten_target, test_whiten_preds))
print(classification_report(test_whiten_target, test_whiten_preds, digits=3))
print("whiten F1 score:",f1_score(test_whiten_target, test_whiten_preds, average='macro'))
print("whiten Precision: ",precision_score(test_whiten_target, test_whiten_preds, average="macro"))
print("whiten Recall: ",recall_score(test_whiten_target, test_whiten_preds, average="macro"))    
print("whiten Confusion matrix: \n",confusion_matrix(test_whiten_target, test_whiten_preds))




############### Env noise
envn test accuracy:  0.99
              precision    recall  f1-score   support

           0      0.992     0.988     0.990       500
           1      0.988     0.992     0.990       500

    accuracy                          0.990      1000
   macro avg      0.990     0.990     0.990      1000
weighted avg      0.990     0.990     0.990      1000

envn F1 score: 0.98999995999984
envn Precision:  0.990007840125442
envn Recall:  0.99
envn Confusion matrix: 
 [[494   6]
 [  4 496]]
############### Dem noise
demn test accuracy:  0.995
              precision    recall  f1-score   support

           0      1.000     0.990     0.995       500
           1      0.990     1.000     0.995       500

    accuracy                          0.995      1000
   macro avg      0.995     0.995     0.995      1000
weighted avg      0.995     0.995     0.995      1000

envn F1 score: 0.9949998749968749
envn Precision:  0.995049504950495
envn Recall:  0.995
envn Confusion mat

In [12]:
#censored performance
from sklearn.metrics import accuracy_score

test_demn_preds = np.argmax(preds_demn, axis=2)
test_whiten_preds = np.argmax(preds_whiten, axis=2)
test_envn_preds = np.argmax(preds_envn, axis=2)


from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print("############### Env noise")
print("envn test accuracy: ", accuracy_score(test_envn_target, test_envn_preds))
print(classification_report(test_envn_target, test_envn_preds, digits=3))
print("envn F1 score:",f1_score(test_envn_target, test_envn_preds, average='macro'))
print("envn Precision: ",precision_score(test_envn_target, test_envn_preds, average="macro"))
print("envn Recall: ",recall_score(test_envn_target, test_envn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_envn_target, test_envn_preds))

print("############### Dem noise")
print("demn test accuracy: ", accuracy_score(test_demn_target, test_demn_preds))
print(classification_report(test_demn_target, test_demn_preds, digits=3))
print("envn F1 score:",f1_score(test_demn_target, test_demn_preds, average='macro'))
print("envn Precision: ",precision_score(test_demn_target, test_demn_preds, average="macro"))
print("envn Recall: ",recall_score(test_demn_target, test_demn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_demn_target, test_demn_preds))

print("############### White noise")
print("whiten test accuracy: ", accuracy_score(test_whiten_target, test_whiten_preds))
print(classification_report(test_whiten_target, test_whiten_preds, digits=3))
print("whiten F1 score:",f1_score(test_whiten_target, test_whiten_preds, average='macro'))
print("whiten Precision: ",precision_score(test_whiten_target, test_whiten_preds, average="macro"))
print("whiten Recall: ",recall_score(test_whiten_target, test_whiten_preds, average="macro"))    
print("whiten Confusion matrix: \n",confusion_matrix(test_whiten_target, test_whiten_preds))




############### Env noise
envn test accuracy:  0.536
              precision    recall  f1-score   support

           0      1.000     0.072     0.134       500
           1      0.519     1.000     0.683       500

    accuracy                          0.536      1000
   macro avg      0.759     0.536     0.409      1000
weighted avg      0.759     0.536     0.409      1000

envn F1 score: 0.4086942337492864
envn Precision:  0.7593360995850622
envn Recall:  0.536
envn Confusion matrix: 
 [[ 36 464]
 [  0 500]]
############### Dem noise
demn test accuracy:  0.545
              precision    recall  f1-score   support

           0      1.000     0.090     0.165       500
           1      0.524     1.000     0.687       500

    accuracy                          0.545      1000
   macro avg      0.762     0.545     0.426      1000
weighted avg      0.762     0.545     0.426      1000

envn F1 score: 0.42621141902329834
envn Precision:  0.7617801047120418
envn Recall:  0.545
envn Confus