### test reza and bauch - bauch test set

In [6]:
import pickle
# load the data
with open("preproccessed_data_uncensored.pickle", "rb") as f:
    data_dic = pickle.load(f)

test = data_dic['test']
test_target = data_dic['test_target']

In [7]:
with open("bauch_apply_bauch_test_uncen.pickle", "rb") as f:
    test_preds = pickle.load(f)

In [3]:
import numpy as np

np.unique(test_target)

array([0, 1, 2, 3])

In [8]:
test = np.array(test)
test_target = np.array(test_target)

filter_list = [t>1 for t in test_target]
test = test[filter_list]
test_target = test_target[filter_list]

# test_target[test_target == 3] = 0
# test_target[test_target == 2] = 1

In [9]:
test_preds = np.array(test_preds)
test_preds = test_preds[filter_list]

In [ ]:
test[0]

In [10]:
#performance on bauch uncensored
from sklearn.metrics import accuracy_score
test_preds = np.argmax(test_preds, axis=2)
# test_preds[test_preds == 3] = 0
# test_preds[test_preds == 2] = 1
print("accuracy: ", accuracy_score(test_target, test_preds))

from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print(classification_report(test_target, test_preds, digits=3))
print("F1 score:",f1_score(test_target, test_preds, average='macro'))
print("Precision: ",precision_score(test_target, test_preds, average="macro"))
print("Recall: ",recall_score(test_target, test_preds, average="macro"))    
print("Confusion matrix: \n",confusion_matrix(test_target, test_preds))

accuracy:  0.486
              precision    recall  f1-score   support

           2      0.493     0.972     0.654       500
           3      0.000     0.000     0.000       500

    accuracy                          0.486      1000
   macro avg      0.246     0.486     0.327      1000
weighted avg      0.246     0.486     0.327      1000

F1 score: 0.32705248990578734
Precision:  0.24645030425963488
Recall:  0.486
Confusion matrix: 
 [[486  14]
 [500   0]]


In [36]:
with open("reza_apply_bauch_test_uncen.pickle", "rb") as f:
    test_preds = pickle.load(f)

In [37]:
test_preds = np.array(test_preds)
test_preds = test_preds[filter_list]

array([[-0.00454521],
       [-0.01702688],
       [-0.01614218],
       ...,
       [-0.00547889],
       [ 0.00033639],
       [-0.00284049]])

In [39]:
#performance on bauch uncensored
from sklearn.metrics import accuracy_score
test_preds = np.argmax(test_preds, axis=2)
# test_preds[test_preds == 3] = 0
# test_preds[test_preds == 2] = 1
print("accuracy: ", accuracy_score(test_target, test_preds))

from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print(classification_report(test_target, test_preds, digits=3))
print("F1 score:",f1_score(test_target, test_preds, average='macro'))
print("Precision: ",precision_score(test_target, test_preds, average="macro"))
print("Recall: ",recall_score(test_target, test_preds, average="macro"))    
print("Confusion matrix: \n",confusion_matrix(test_target, test_preds))

accuracy:  0.5
              precision    recall  f1-score   support

           0      0.000     0.000     0.000       500
           1      0.500     1.000     0.667       500

    accuracy                          0.500      1000
   macro avg      0.250     0.500     0.333      1000
weighted avg      0.250     0.500     0.333      1000

F1 score: 0.3333333333333333
Precision:  0.25
Recall:  0.5
Confusion matrix: 
 [[  0 500]
 [  0 500]]


/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rezmiry/venv/lib/python3.10/site-p

### test noise induced - reza and bauch model

In [1]:
import pickle
with open("train_amit/envn_uncen_resids_dic.pickle", "rb") as f:
    data_dic_t1 = pickle.load(f)

with open("train_amit/whiten_uncen_resids_dic.pickle", "rb") as f:
    data_dic_t2 = pickle.load(f)

with open("train_amit/demn_uncen_resids_dic.pickle", "rb") as f:
    data_dic_t3 = pickle.load(f)

In [2]:
test_envn = data_dic_t1['test']
test_envn_target = data_dic_t1['test_target']
test_whiten = data_dic_t2['test']
test_whiten_target = data_dic_t2['test_target']
test_demn = data_dic_t3['test']
test_demn_target = data_dic_t3['test_target']

In [4]:
import pickle
with open("reza_apply_test_demn_uncen.pickle", "rb") as f:
    preds_demn = pickle.load(f)

with open("reza_apply_test_whiten_uncen.pickle", "rb") as f:
    preds_whiten = pickle.load(f)

with open("reza_apply_test_envn_uncen.pickle", "rb") as f:
    preds_envn = pickle.load(f)


In [5]:
# uncensored prerofmance
from sklearn.metrics import accuracy_score
import numpy as np

test_demn_preds = np.argmax(preds_demn, axis=2)
test_whiten_preds = np.argmax(preds_whiten, axis=2)
test_envn_preds = np.argmax(preds_envn, axis=2)


from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print("############### Env noise")
print("envn test accuracy: ", accuracy_score(test_envn_target, test_envn_preds))
print(classification_report(test_envn_target, test_envn_preds, digits=3))
print("envn F1 score:",f1_score(test_envn_target, test_envn_preds, average='macro'))
print("envn Precision: ",precision_score(test_envn_target, test_envn_preds, average="macro"))
print("envn Recall: ",recall_score(test_envn_target, test_envn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_envn_target, test_envn_preds))

print("############### Dem noise")
print("demn test accuracy: ", accuracy_score(test_demn_target, test_demn_preds))
print(classification_report(test_demn_target, test_demn_preds, digits=3))
print("envn F1 score:",f1_score(test_demn_target, test_demn_preds, average='macro'))
print("envn Precision: ",precision_score(test_demn_target, test_demn_preds, average="macro"))
print("envn Recall: ",recall_score(test_demn_target, test_demn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_demn_target, test_demn_preds))

print("############### White noise")
print("whiten test accuracy: ", accuracy_score(test_whiten_target, test_whiten_preds))
print(classification_report(test_whiten_target, test_whiten_preds, digits=3))
print("whiten F1 score:",f1_score(test_whiten_target, test_whiten_preds, average='macro'))
print("whiten Precision: ",precision_score(test_whiten_target, test_whiten_preds, average="macro"))
print("whiten Recall: ",recall_score(test_whiten_target, test_whiten_preds, average="macro"))    
print("whiten Confusion matrix: \n",confusion_matrix(test_whiten_target, test_whiten_preds))




############### Env noise
envn test accuracy:  0.996
              precision    recall  f1-score   support

           0      0.992     1.000     0.996       500
           1      1.000     0.992     0.996       500

    accuracy                          0.996      1000
   macro avg      0.996     0.996     0.996      1000
weighted avg      0.996     0.996     0.996      1000

envn F1 score: 0.995999935998976
envn Precision:  0.996031746031746
envn Recall:  0.996
envn Confusion matrix: 
 [[500   0]
 [  4 496]]
############### Dem noise
demn test accuracy:  0.998
              precision    recall  f1-score   support

           0      0.998     0.998     0.998       500
           1      0.998     0.998     0.998       500

    accuracy                          0.998      1000
   macro avg      0.998     0.998     0.998      1000
weighted avg      0.998     0.998     0.998      1000

envn F1 score: 0.998
envn Precision:  0.998
envn Recall:  0.998
envn Confusion matrix: 
 [[499   1]
 [  

In [6]:
import pickle
with open("bauch_apply_test_demn_uncen.pickle", "rb") as f:
    preds_demn = pickle.load(f)

with open("bauch_apply_test_whiten_uncen.pickle", "rb") as f:
    preds_whiten = pickle.load(f)

with open("bauch_apply_test_envn_uncen.pickle", "rb") as f:
    preds_envn = pickle.load(f)


In [7]:
# uncensored prerofmance
from sklearn.metrics import accuracy_score
import numpy as np

test_demn_preds = np.argmax(preds_demn, axis=2)
test_whiten_preds = np.argmax(preds_whiten, axis=2)
test_envn_preds = np.argmax(preds_envn, axis=2)


from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 

print("############### Env noise")
print("envn test accuracy: ", accuracy_score(test_envn_target, test_envn_preds))
print(classification_report(test_envn_target, test_envn_preds, digits=3))
print("envn F1 score:",f1_score(test_envn_target, test_envn_preds, average='macro'))
print("envn Precision: ",precision_score(test_envn_target, test_envn_preds, average="macro"))
print("envn Recall: ",recall_score(test_envn_target, test_envn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_envn_target, test_envn_preds))

print("############### Dem noise")
print("demn test accuracy: ", accuracy_score(test_demn_target, test_demn_preds))
print(classification_report(test_demn_target, test_demn_preds, digits=3))
print("envn F1 score:",f1_score(test_demn_target, test_demn_preds, average='macro'))
print("envn Precision: ",precision_score(test_demn_target, test_demn_preds, average="macro"))
print("envn Recall: ",recall_score(test_demn_target, test_demn_preds, average="macro"))    
print("envn Confusion matrix: \n",confusion_matrix(test_demn_target, test_demn_preds))

print("############### White noise")
print("whiten test accuracy: ", accuracy_score(test_whiten_target, test_whiten_preds))
print(classification_report(test_whiten_target, test_whiten_preds, digits=3))
print("whiten F1 score:",f1_score(test_whiten_target, test_whiten_preds, average='macro'))
print("whiten Precision: ",precision_score(test_whiten_target, test_whiten_preds, average="macro"))
print("whiten Recall: ",recall_score(test_whiten_target, test_whiten_preds, average="macro"))    
print("whiten Confusion matrix: \n",confusion_matrix(test_whiten_target, test_whiten_preds))




############### Env noise
envn test accuracy:  0.752
              precision    recall  f1-score   support

           0      0.811     0.892     0.850       500
           1      1.000     0.612     0.759       500
           2      0.000     0.000     0.000         0
           3      0.000     0.000     0.000         0

    accuracy                          0.752      1000
   macro avg      0.453     0.376     0.402      1000
weighted avg      0.905     0.752     0.804      1000

envn F1 score: 0.40220725511048094
envn Precision:  0.45272727272727276
envn Recall:  0.376
envn Confusion matrix: 
 [[446   0   6  48]
 [104 306  85   5]
 [  0   0   0   0]
 [  0   0   0   0]]
############### Dem noise
demn test accuracy:  0.834
              precision    recall  f1-score   support

           0      0.900     0.812     0.854       500
           1      1.000     0.856     0.922       500
           2      0.000     0.000     0.000         0
           3      0.000     0.000     0.000     

/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rezmiry/venv/lib/python3.10/site-packages/sklearn/metrics/